version: '3'
services: 
  web:
    image: docker-node-express-mongoapp
    build: ./theSite
    command: node index.js
    ports:
      - "3000:3000"
    volumes:
      - ./theSite:/usr/src/app
      - /user/src/app/node_modules
    depends_on:
      - "mongo"
  # THE MONGO BELOW NEEDS TO MATCH WITH the DATABASE_CONNECTION VARIABLE
  mongo:
    image: "mongo"
    ports: 
    - "27017:27017"

  adminmongo:
    image: "mrvautin/adminmongo"
    ports: 
      - "1234:1234"

